apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: art-bot
  name: art-bot
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: registry.fedoraproject.org/fedora:33
    name: "fedora-33"
    referencePolicy:
      type: Source
